version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Singapore
    open-pull-requests-limit: 10
    target-branch: "develop"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Singapore
    open-pull-requests-limit: 10
    target-branch: "develop"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Singapore
    open-pull-requests-limit: 10
    target-branch: "develop"
  - package-ecosystem: "docker"
    directory: "/docker/production/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Singapore
    open-pull-requests-limit: 10
    target-branch: "develop"