name: CD
on:
  workflow_call:
    inputs:
      environment-name:
        type: string
        required: true
      aws-region:
        type: string
        required: true
    secrets:
      GH_ACTIONS_ROLE_ARN:
        required: true
      AWS_BUCKET:
        required: true
      CLOUDFRONT_DISTRIBUTION:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ inputs.environment-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #############################
      # Configure AWS Credentials #
      #############################
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }} 
          role-session-name: GithubActions
          aws-region: ${{ inputs.aws-region }}
          audience: sts.amazonaws.com
          mask-aws-account-id: false

      #############################
      # S3 Upload                 #
      #############################
      - name: S3 Upload
        run: |
          aws s3 sync --delete ./schema/ s3://$AWS_BUCKET/opencerts/ --exclude "*" --include "*.json"
        env:
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}

      #############################
      # Invalidate Cloudfront     #
      #############################
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths '/*'
        env:
          CLOUDFRONT_DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}